[workspace]
members = [".", "rotom-lsp"]
resolver = "2"

[package]
name = "rotom"
version = "0.1.0"
edition = "2024"

[lib]
name = "rotom"
path = "src/lib.rs"

[[bin]]
name = "rotom"
path = "src/main.rs"

[dependencies]
chrono = {version = "0.4.42", features = ["serde"]}
clap = { version = "4.5.51", features = ["derive"] }
codespan-reporting = "0.13.1"
dashmap = "6.1.0"
hex = "0.4"
lsp-types = { version = "0.97", optional = true }
linked_hash_set = "0.1.6"
rayon = "1.11.0"
regex = "1.12.2"
serde = {version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10"
minreq = { version = "2.14.1", features = ["https-rustls"] }
thiserror = "2.0"
toml = "0.8.19"
uxie = "0.6.12"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
indicatif = { version = "0.18.4", features = ["rayon"] }

[build-dependencies]
minreq = { version = "2.14.1", features = ["https-rustls"] }
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }

[dev-dependencies]
sha2 = "0.10"
hex = "0.4"
tempfile = "3.23.0"

[features]
lsp-types = ["dep:lsp-types"]

[profile.release]
debug = true
[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
use_self = "allow"
uninlined_format_args = "allow"
option_if_let_else = "allow"
missing_const_for_fn = "allow"
