use crate::database::{GameFamily, game_family_from_hint};
use std::fs;
use std::io::{Cursor, Read, Seek, Write};
use std::path::{Path, PathBuf};
use uxie::{ProjectType, Workspace};

use super::config::{
    DatabaseConfig, PathsConfig, ProjectMetadata, ProjectTypeConfig, RotomConfig, WorkspaceConfig,
    load_config,
};
use super::convert::{convert_project, find_convertible_files};
use super::error::{ProjectError, Result};

pub const LATEST_COMMAND_DATABASE_URL: &str = "https://github.com/DS-Pokemon-Rom-Editor/scrcmd-database/releases/latest/download/db-latest.zip";

const ROTOM_DIR: &str = ".rotom";
const COMMAND_DATABASE_DIR: &str = ".rotom/command_database";
const CACHE_DIR: &str = ".rotom/cache";
const STATUS_DIR: &str = ".rotom/status";
const EMBEDDED_COMMAND_DATABASE_ZIP: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/embedded-command-database.zip"));

#[derive(Debug, Clone)]
pub struct InitReport {
    pub used_embedded_database: bool,
    pub reused_paths: Vec<&'static str>,
    pub convertible_files_detected: usize,
    pub converted_files: usize,
}

#[derive(Debug, Clone, Default)]
pub struct InitOptions {
    pub interactive: bool,
    pub game_hint: Option<String>,
    pub database_path: Option<PathBuf>,
}

#[derive(Debug, Clone)]
struct WorkspaceInfo {
    project_type: ProjectTypeConfig,
    game_family: Option<GameFamily>,
    source_roots: Vec<String>,
    include_roots: Vec<String>,
    binary_roots: Vec<String>,
}

pub fn run_init(root: Option<PathBuf>) -> Result<InitReport> {
    run_init_with_options(root, InitOptions::default())
}

pub fn run_init_with_options(root: Option<PathBuf>, options: InitOptions) -> Result<InitReport> {
    let InitOptions {
        interactive,
        game_hint,
        database_path,
    } = options;
    let root = match root {
        Some(root) => root,
        None => {
            std::env::current_dir().map_err(|source| ProjectError::CurrentDirectory { source })?
        }
    };
    if !root.exists() {
        fs::create_dir_all(&root).map_err(|source| ProjectError::Io {
            action: "Failed to create directory",
            path: root.clone(),
            source,
        })?;
    }
    let root = root.canonicalize().map_err(|source| ProjectError::Io {
        action: "Failed to resolve",
        path: root,
        source,
    })?;

    let mut reused_paths = Vec::new();
    for path in [
        ROTOM_DIR,
        CACHE_DIR,
        STATUS_DIR,
        COMMAND_DATABASE_DIR,
        "rotom.toml",
    ] {
        if root.join(path).exists() {
            reused_paths.push(path);
        }
    }

    fs::create_dir_all(root.join(ROTOM_DIR)).map_err(|source| ProjectError::Io {
        action: "Failed to create directory",
        path: root.join(ROTOM_DIR),
        source,
    })?;
    fs::create_dir_all(root.join(CACHE_DIR)).map_err(|source| ProjectError::Io {
        action: "Failed to create directory",
        path: root.join(CACHE_DIR),
        source,
    })?;
    fs::create_dir_all(root.join(STATUS_DIR)).map_err(|source| ProjectError::Io {
        action: "Failed to create directory",
        path: root.join(STATUS_DIR),
        source,
    })?;

    let command_database_dir = root.join(COMMAND_DATABASE_DIR);
    let used_embedded_database = ensure_command_database(&command_database_dir)?;

    let workspace = detect_workspace(&root)?;
    let preferred_family = workspace
        .game_family
        .or_else(|| game_hint.as_ref().and_then(game_family_from_hint));
    let default_database_file = if let Some(path) = database_path.as_ref() {
        let path = if path.is_absolute() {
            path.clone()
        } else {
            root.join(path)
        };
        Some(path.strip_prefix(&root).unwrap_or(&path).to_path_buf())
    } else {
        find_default_database_file(&root, &command_database_dir, preferred_family)?
    };

    let config_path = root.join("rotom.toml");
    if !config_path.exists() {
        let config = build_config(&root, &workspace, default_database_file.as_deref());
        let content = toml::to_string_pretty(&config)
            .map_err(|source| ProjectError::SerializeConfig { source })?;
        fs::write(
            &config_path,
            format!("# Generated by `rotom init`\n\n{}", content),
        )
        .map_err(|source| ProjectError::Io {
            action: "Failed to write",
            path: config_path.clone(),
            source,
        })?;
    }

    let config = load_config(&root)?;
    let (convertible_files_detected, converted_files) =
        maybe_convert_existing_sources(&root, &config, interactive)?;

    Ok(InitReport {
        used_embedded_database,
        reused_paths,
        convertible_files_detected,
        converted_files,
    })
}

fn maybe_convert_existing_sources(
    root: &Path,
    config: &RotomConfig,
    interactive: bool,
) -> Result<(usize, usize)> {
    let convertible_files_detected = find_convertible_files(root, config)?.len();
    if !interactive || convertible_files_detected == 0 {
        return Ok((convertible_files_detected, 0));
    }

    let mut stdout = std::io::stdout();
    write!(
        stdout,
        "Convert {} file(s) to .rotom format now? [Y/n] ",
        convertible_files_detected
    )
    .map_err(|source| ProjectError::StdIo {
        action: "Failed to write prompt",
        source,
    })?;
    stdout.flush().map_err(|source| ProjectError::StdIo {
        action: "Failed to flush prompt",
        source,
    })?;

    let mut response = String::new();
    std::io::stdin()
        .read_line(&mut response)
        .map_err(|source| ProjectError::StdIo {
            action: "Failed to read prompt response",
            source,
        })?;
    let answer = response.trim().to_ascii_lowercase();
    if answer.is_empty() || answer == "y" || answer == "yes" {
        Ok((
            convertible_files_detected,
            convert_project(root, config, false)?.converted,
        ))
    } else {
        Ok((convertible_files_detected, 0))
    }
}

fn detect_workspace(root: &Path) -> Result<WorkspaceInfo> {
    let workspace = Workspace::open(root).map_err(|source| ProjectError::Io {
        action: "Failed to open workspace",
        path: root.to_path_buf(),
        source,
    })?;

    Ok(match workspace.project_type {
        ProjectType::Dspre => WorkspaceInfo {
            project_type: ProjectTypeConfig::Dspre,
            game_family: Some(workspace.family),
            source_roots: if root.join("expanded/scripts").exists() {
                vec!["expanded/scripts".to_string()]
            } else if root.join("scripts").exists() {
                vec!["scripts".to_string()]
            } else {
                Vec::new()
            },
            include_roots: Vec::new(),
            binary_roots: [
                "unpacked/data/fielddata/script",
                "unpacked/scripts",
                "scripts",
            ]
            .into_iter()
            .find(|path| root.join(path).exists())
            .map(str::to_string)
            .into_iter()
            .collect(),
        },
        ProjectType::Decomp => {
            let (source_roots, include_roots) = match workspace.family {
                uxie::GameFamily::HGSS => (
                    vec!["files/fielddata/script/scr_seq".to_string()],
                    vec![
                        "include".to_string(),
                        "generated".to_string(),
                        "files".to_string(),
                    ],
                ),
                uxie::GameFamily::Platinum => (
                    vec!["res/field/scripts".to_string()],
                    vec![
                        "include".to_string(),
                        "generated".to_string(),
                        "res/field/scripts".to_string(),
                    ],
                ),
                uxie::GameFamily::DP => unreachable!("decomp detection should not resolve to DP"),
            };
            let binary_roots = source_roots.clone();

            WorkspaceInfo {
                project_type: ProjectTypeConfig::Decomp,
                game_family: Some(workspace.family),
                source_roots,
                include_roots,
                binary_roots,
            }
        }
    })
}

fn build_config(root: &Path, workspace: &WorkspaceInfo, default_db: Option<&Path>) -> RotomConfig {
    RotomConfig {
        format_version: 1,
        project: ProjectMetadata {
            name: root.file_name().map_or_else(
                || "rotom-project".to_string(),
                |name| name.to_string_lossy().to_string(),
            ),
        },
        workspace: WorkspaceConfig {
            project_type: workspace.project_type,
            game_family: workspace.game_family.map(Into::into),
        },
        paths: PathsConfig {
            database_dir: COMMAND_DATABASE_DIR.to_string(),
            cache_dir: CACHE_DIR.to_string(),
            status_dir: STATUS_DIR.to_string(),
            source_roots: workspace.source_roots.clone(),
            include_roots: workspace.include_roots.clone(),
            binary_roots: workspace.binary_roots.clone(),
        },
        database: default_db.map(|path| DatabaseConfig {
            default_file: path.display().to_string(),
        }),
    }
}

fn ensure_command_database(dir: &Path) -> Result<bool> {
    if dir.exists()
        && fs::read_dir(dir)
            .map_err(|source| ProjectError::Io {
                action: "Failed to read directory",
                path: dir.to_path_buf(),
                source,
            })?
            .next()
            .transpose()
            .map_err(|source| ProjectError::Io {
                action: "Failed to read directory entry",
                path: dir.to_path_buf(),
                source,
            })?
            .is_some()
    {
        return Ok(false);
    }

    let temp_dir = dir.with_extension("bootstrap");
    if temp_dir.exists() {
        fs::remove_dir_all(&temp_dir).map_err(|source| ProjectError::Io {
            action: "Failed to remove directory",
            path: temp_dir.clone(),
            source,
        })?;
    }
    fs::create_dir_all(&temp_dir).map_err(|source| ProjectError::Io {
        action: "Failed to create directory",
        path: temp_dir.clone(),
        source,
    })?;

    let used_embedded = if let Ok(bytes) = download_latest_database_zip() {
        unpack_zip(Cursor::new(bytes), &temp_dir)?;
        false
    } else {
        unpack_zip(Cursor::new(EMBEDDED_COMMAND_DATABASE_ZIP), &temp_dir)?;
        true
    };

    if dir.exists() {
        fs::remove_dir_all(dir).map_err(|source| ProjectError::Io {
            action: "Failed to remove directory",
            path: dir.to_path_buf(),
            source,
        })?;
    }
    fs::rename(&temp_dir, dir).map_err(|source| ProjectError::Io {
        action: "Failed to rename",
        path: dir.to_path_buf(),
        source,
    })?;
    Ok(used_embedded)
}

fn download_latest_database_zip() -> Result<Vec<u8>> {
    let response = minreq::get(LATEST_COMMAND_DATABASE_URL)
        .with_header("User-Agent", format!("rotom/{}", env!("CARGO_PKG_VERSION")))
        .with_timeout(20)
        .send()
        .map_err(|source| ProjectError::DownloadDatabase { source })?;
    Ok(response.into_bytes())
}

fn unpack_zip<R: Read + Seek>(reader: R, out_dir: &Path) -> Result<()> {
    let mut archive = zip::ZipArchive::new(reader)?;
    for index in 0..archive.len() {
        let mut entry = archive.by_index(index)?;
        let Some(name) = entry.enclosed_name() else {
            continue;
        };
        let path = out_dir.join(name);

        if entry.is_dir() {
            fs::create_dir_all(&path).map_err(|source| ProjectError::Io {
                action: "Failed to create directory",
                path: path.clone(),
                source,
            })?;
            continue;
        }

        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|source| ProjectError::Io {
                action: "Failed to create directory",
                path: parent.to_path_buf(),
                source,
            })?;
        }

        let mut file = fs::File::create(&path).map_err(|source| ProjectError::Io {
            action: "Failed to create file",
            path: path.clone(),
            source,
        })?;
        std::io::copy(&mut entry, &mut file).map_err(|source| ProjectError::Io {
            action: "Failed to unpack archive entry into",
            path,
            source,
        })?;
    }

    Ok(())
}

fn find_default_database_file(
    root: &Path,
    database_dir: &Path,
    preferred_family: Option<GameFamily>,
) -> Result<Option<PathBuf>> {
    let mut files = Vec::new();
    collect_v2_files(database_dir, &mut files)?;
    files.sort();

    if let Some(preferred_family) = preferred_family
        && let Some(file) = files
            .iter()
            .find(|file| game_family_from_hint(file.to_string_lossy()) == Some(preferred_family))
    {
        return Ok(Some(
            file.strip_prefix(root)
                .unwrap_or(file.as_path())
                .to_path_buf(),
        ));
    }

    Ok((files.len() == 1).then(|| {
        files[0]
            .strip_prefix(root)
            .unwrap_or(files[0].as_path())
            .to_path_buf()
    }))
}

fn collect_v2_files(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(dir).map_err(|source| ProjectError::Io {
        action: "Failed to read directory",
        path: dir.to_path_buf(),
        source,
    })? {
        let path = entry
            .map_err(|source| ProjectError::Io {
                action: "Failed to read directory entry",
                path: dir.to_path_buf(),
                source,
            })?
            .path();
        if path.is_dir() {
            collect_v2_files(&path, out)?;
        } else if path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.ends_with("_v2.json"))
        {
            out.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::tempdir;
    use zip::write::FileOptions;

    fn write_database(path: &Path, version: &str) {
        fs::write(
            path,
            format!(
                r#"{{
  "meta": {{ "version": "{version}" }},
  "commands": {{}}
}}"#
            ),
        )
        .unwrap();
    }

    #[test]
    fn run_init_writes_config_from_existing_db_dir() {
        let root = tempdir().unwrap();
        fs::create_dir_all(root.path().join("res/field/scripts")).unwrap();
        fs::write(root.path().join("res/field/scripts/scripts.order"), "").unwrap();
        fs::create_dir_all(root.path().join(COMMAND_DATABASE_DIR)).unwrap();
        write_database(
            &root
                .path()
                .join(COMMAND_DATABASE_DIR)
                .join("platinum_v2.json"),
            "Platinum",
        );

        let report = run_init(Some(root.path().to_path_buf())).unwrap();

        assert!(!report.used_embedded_database);
        assert!(report.reused_paths.contains(&COMMAND_DATABASE_DIR));
        assert_eq!(report.converted_files, 0);

        let config = fs::read_to_string(root.path().join("rotom.toml")).unwrap();
        assert!(config.contains("project_type = \"decomp\""));
        assert!(config.contains("game_family = \"platinum\""));
        assert!(config.contains("default_file = \".rotom/command_database/platinum_v2.json\""));
        assert!(!config.contains("provider = "));
    }

    #[test]
    fn run_init_non_interactive_skips_conversion_prompt_without_error() {
        let root = tempdir().unwrap();
        fs::create_dir_all(root.path().join("res/field/scripts")).unwrap();
        fs::write(root.path().join("res/field/scripts/scripts.order"), "").unwrap();
        fs::write(
            root.path().join("res/field/scripts/test.s"),
            "ScriptEntry Test\nScriptEntryEnd\n\nTest:\n    End\n",
        )
        .unwrap();
        fs::create_dir_all(root.path().join(COMMAND_DATABASE_DIR)).unwrap();
        write_database(
            &root
                .path()
                .join(COMMAND_DATABASE_DIR)
                .join("platinum_v2.json"),
            "Platinum",
        );

        let report = run_init_with_options(
            Some(root.path().to_path_buf()),
            InitOptions {
                interactive: false,
                ..InitOptions::default()
            },
        )
        .unwrap();

        assert_eq!(report.convertible_files_detected, 1);
        assert_eq!(report.converted_files, 0);
        assert!(root.path().join("res/field/scripts/test.s").exists());
        assert!(!root.path().join("res/field/scripts/test.rotom").exists());
    }

    #[test]
    fn run_init_errors_when_workspace_cannot_be_opened() {
        let root = tempdir().unwrap();
        fs::create_dir_all(root.path().join(COMMAND_DATABASE_DIR)).unwrap();
        write_database(
            &root
                .path()
                .join(COMMAND_DATABASE_DIR)
                .join("platinum_v2.json"),
            "Platinum",
        );

        let error = run_init(Some(root.path().to_path_buf())).unwrap_err();
        assert!(
            error.to_string().contains("Failed to open workspace"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn unpack_zip_extracts_database_file() {
        let root = tempdir().unwrap();
        let zip_path = root.path().join("db.zip");
        let zip_file = fs::File::create(&zip_path).unwrap();
        let mut zip = zip::ZipWriter::new(zip_file);
        let options: FileOptions<'_, ()> = FileOptions::default();
        zip.start_file("platinum_v2.json", options).unwrap();
        zip.write_all(
            br#"{
  "meta": { "version": "Platinum" },
  "commands": {}
}"#,
        )
        .unwrap();
        zip.finish().unwrap();

        let out = root.path().join("out");
        fs::create_dir_all(&out).unwrap();
        unpack_zip(fs::File::open(zip_path).unwrap(), &out).unwrap();

        assert!(out.join("platinum_v2.json").exists());
    }

    #[test]
    fn embedded_database_archive_contains_v2_files() {
        let out = tempdir().unwrap();
        unpack_zip(Cursor::new(EMBEDDED_COMMAND_DATABASE_ZIP), out.path()).unwrap();

        let mut files = Vec::new();
        collect_v2_files(out.path(), &mut files).unwrap();
        assert!(!files.is_empty());
    }
}
