use crate::database::{GameFamily, GameFamilyExt, game_family_from_hint};
use serde::Serialize;
use std::error::Error;
use std::fs;
use std::io::{Cursor, Read, Seek};
use std::path::{Path, PathBuf};
use uxie::{ProjectType, Workspace};

pub const LATEST_COMMAND_DATABASE_URL: &str = "https://github.com/DS-Pokemon-Rom-Editor/scrcmd-database/releases/latest/download/db-latest.zip";

const ROTOM_DIR: &str = ".rotom";
const COMMAND_DATABASE_DIR: &str = ".rotom/command_database";
const CACHE_DIR: &str = ".rotom/cache";
const STATUS_DIR: &str = ".rotom/status";
const EMBEDDED_COMMAND_DATABASE_ZIP: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/embedded-command-database.zip"));

#[derive(Debug, Clone)]
pub struct InitReport {
    pub used_embedded_database: bool,
    pub reused_paths: Vec<&'static str>,
}

#[derive(Debug, Clone)]
struct WorkspaceInfo {
    project_type: Option<ProjectType>,
    game_family: Option<GameFamily>,
    source_roots: Vec<String>,
    include_roots: Vec<String>,
    binary_roots: Vec<String>,
}

#[derive(Debug, Serialize)]
struct RotomConfig {
    format_version: u32,
    project: ProjectConfig,
    workspace: WorkspaceConfig,
    paths: PathsConfig,
    #[serde(skip_serializing_if = "Option::is_none")]
    database: Option<DatabaseConfig>,
}

#[derive(Debug, Serialize)]
struct ProjectConfig {
    name: String,
}

#[derive(Debug, Serialize)]
struct WorkspaceConfig {
    project_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    game_family: Option<String>,
}

#[derive(Debug, Serialize)]
struct PathsConfig {
    database_dir: String,
    cache_dir: String,
    status_dir: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    source_roots: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    include_roots: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    binary_roots: Vec<String>,
}

#[derive(Debug, Serialize)]
struct DatabaseConfig {
    default_file: String,
}

pub fn run_init(root: Option<PathBuf>) -> Result<InitReport, Box<dyn Error>> {
    let root =
        root.unwrap_or_else(|| std::env::current_dir().expect("failed to get current directory"));
    if !root.exists() {
        fs::create_dir_all(&root)?;
    }
    let root = root.canonicalize()?;

    let mut reused_paths = Vec::new();
    for path in [
        ROTOM_DIR,
        CACHE_DIR,
        STATUS_DIR,
        COMMAND_DATABASE_DIR,
        "rotom.toml",
    ] {
        if root.join(path).exists() {
            reused_paths.push(path);
        }
    }

    fs::create_dir_all(root.join(ROTOM_DIR))?;
    fs::create_dir_all(root.join(CACHE_DIR))?;
    fs::create_dir_all(root.join(STATUS_DIR))?;

    let command_database_dir = root.join(COMMAND_DATABASE_DIR);
    let used_embedded_database = ensure_command_database(&command_database_dir)?;

    let workspace = detect_workspace(&root);
    let default_database_file =
        find_default_database_file(&root, &command_database_dir, workspace.game_family)?;

    let config_path = root.join("rotom.toml");
    if !config_path.exists() {
        let config = build_config(&root, &workspace, default_database_file.as_deref());
        fs::write(
            &config_path,
            format!(
                "# Generated by `rotom init`\n\n{}",
                toml::to_string_pretty(&config)?
            ),
        )?;
    }

    Ok(InitReport {
        used_embedded_database,
        reused_paths,
    })
}

fn detect_workspace(root: &Path) -> WorkspaceInfo {
    let Ok(workspace) = Workspace::open(root) else {
        return WorkspaceInfo {
            project_type: None,
            game_family: None,
            source_roots: Vec::new(),
            include_roots: Vec::new(),
            binary_roots: Vec::new(),
        };
    };

    match workspace.project_type {
        ProjectType::Dspre => WorkspaceInfo {
            project_type: Some(ProjectType::Dspre),
            game_family: Some(workspace.family.into()),
            source_roots: if root.join("expanded/scripts").exists() {
                vec!["expanded/scripts".to_string()]
            } else if root.join("scripts").exists() {
                vec!["scripts".to_string()]
            } else {
                Vec::new()
            },
            include_roots: Vec::new(),
            binary_roots: [
                "unpacked/data/fielddata/script",
                "unpacked/scripts",
                "scripts",
            ]
            .into_iter()
            .filter(|path| root.join(path).exists())
            .map(str::to_string)
            .collect(),
        },
        ProjectType::Decomp => {
            let (source_roots, include_roots) = match workspace.family {
                uxie::GameFamily::HGSS => (
                    vec!["files/fielddata/script/scr_seq".to_string()],
                    vec![
                        "include".to_string(),
                        "generated".to_string(),
                        "files".to_string(),
                    ],
                ),
                uxie::GameFamily::Platinum => (
                    vec!["res/field/scripts".to_string()],
                    vec![
                        "include".to_string(),
                        "generated".to_string(),
                        "res/field/scripts".to_string(),
                    ],
                ),
                uxie::GameFamily::DP => unreachable!("decomp detection should not resolve to DP"),
            };

            WorkspaceInfo {
                project_type: Some(ProjectType::Decomp),
                game_family: Some(workspace.family.into()),
                source_roots,
                include_roots,
                binary_roots: Vec::new(),
            }
        }
    }
}

fn build_config(root: &Path, workspace: &WorkspaceInfo, default_db: Option<&Path>) -> RotomConfig {
    RotomConfig {
        format_version: 1,
        project: ProjectConfig {
            name: root
                .file_name()
                .map(|name| name.to_string_lossy().to_string())
                .unwrap_or_else(|| "rotom-project".to_string()),
        },
        workspace: WorkspaceConfig {
            project_type: match workspace.project_type {
                Some(ProjectType::Dspre) => "dspre".to_string(),
                Some(ProjectType::Decomp) => "decomp".to_string(),
                None => "generic".to_string(),
            },
            game_family: workspace
                .game_family
                .map(|family| family.config_name().to_string()),
        },
        paths: PathsConfig {
            database_dir: COMMAND_DATABASE_DIR.to_string(),
            cache_dir: CACHE_DIR.to_string(),
            status_dir: STATUS_DIR.to_string(),
            source_roots: workspace.source_roots.clone(),
            include_roots: workspace.include_roots.clone(),
            binary_roots: workspace.binary_roots.clone(),
        },
        database: default_db.map(|path| DatabaseConfig {
            default_file: path.display().to_string(),
        }),
    }
}

fn ensure_command_database(dir: &Path) -> Result<bool, Box<dyn Error>> {
    if dir.exists() && fs::read_dir(dir)?.next().transpose()?.is_some() {
        return Ok(false);
    }

    let temp_dir = dir.with_extension("bootstrap");
    if temp_dir.exists() {
        fs::remove_dir_all(&temp_dir)?;
    }
    fs::create_dir_all(&temp_dir)?;

    let used_embedded = match download_latest_database_zip() {
        Ok(bytes) => {
            unpack_zip(Cursor::new(bytes), &temp_dir)?;
            false
        }
        Err(_) => {
            unpack_zip(Cursor::new(EMBEDDED_COMMAND_DATABASE_ZIP), &temp_dir)?;
            true
        }
    };

    if dir.exists() {
        fs::remove_dir_all(dir)?;
    }
    fs::rename(&temp_dir, dir)?;
    Ok(used_embedded)
}

fn download_latest_database_zip() -> Result<Vec<u8>, Box<dyn Error>> {
    let response = minreq::get(LATEST_COMMAND_DATABASE_URL)
        .with_header(
            "User-Agent",
            &format!("rotom/{}", env!("CARGO_PKG_VERSION")),
        )
        .with_timeout(20)
        .send()?;
    Ok(response.into_bytes())
}

fn unpack_zip<R: Read + Seek>(reader: R, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let mut archive = zip::ZipArchive::new(reader)?;
    for index in 0..archive.len() {
        let mut entry = archive.by_index(index)?;
        let Some(name) = entry.enclosed_name() else {
            continue;
        };
        let path = out_dir.join(name);

        if entry.is_dir() {
            fs::create_dir_all(&path)?;
            continue;
        }

        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        let mut file = fs::File::create(path)?;
        std::io::copy(&mut entry, &mut file)?;
    }

    Ok(())
}

fn find_default_database_file(
    root: &Path,
    database_dir: &Path,
    preferred_family: Option<GameFamily>,
) -> Result<Option<PathBuf>, Box<dyn Error>> {
    let mut files = Vec::new();
    collect_v2_files(database_dir, &mut files)?;
    files.sort();

    if let Some(preferred_family) = preferred_family {
        if let Some(file) = files
            .iter()
            .find(|file| game_family_from_hint(file.to_string_lossy()) == Some(preferred_family))
        {
            return Ok(Some(
                file.strip_prefix(root)
                    .unwrap_or(file.as_path())
                    .to_path_buf(),
            ));
        }
    }

    Ok((files.len() == 1).then(|| {
        files[0]
            .strip_prefix(root)
            .unwrap_or(files[0].as_path())
            .to_path_buf()
    }))
}

fn collect_v2_files(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_v2_files(&path, out)?;
        } else if path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.ends_with("_v2.json"))
        {
            out.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::tempdir;
    use zip::write::FileOptions;

    fn write_database(path: &Path, version: &str) {
        fs::write(
            path,
            format!(
                r#"{{
  "meta": {{ "version": "{version}" }},
  "commands": {{}}
}}"#
            ),
        )
        .unwrap();
    }

    #[test]
    fn run_init_writes_config_from_existing_db_dir() {
        let root = tempdir().unwrap();
        fs::create_dir_all(root.path().join("res/field/scripts")).unwrap();
        fs::write(root.path().join("res/field/scripts/scripts.order"), "").unwrap();
        fs::create_dir_all(root.path().join(COMMAND_DATABASE_DIR)).unwrap();
        write_database(
            &root
                .path()
                .join(COMMAND_DATABASE_DIR)
                .join("platinum_v2.json"),
            "Platinum",
        );

        let report = run_init(Some(root.path().to_path_buf())).unwrap();

        assert!(!report.used_embedded_database);
        assert!(report.reused_paths.contains(&COMMAND_DATABASE_DIR));

        let config = fs::read_to_string(root.path().join("rotom.toml")).unwrap();
        assert!(config.contains("project_type = \"decomp\""));
        assert!(config.contains("game_family = \"platinum\""));
        assert!(config.contains("default_file = \".rotom/command_database/platinum_v2.json\""));
        assert!(!config.contains("provider = "));
    }

    #[test]
    fn unpack_zip_extracts_database_file() {
        let root = tempdir().unwrap();
        let zip_path = root.path().join("db.zip");
        let zip_file = fs::File::create(&zip_path).unwrap();
        let mut zip = zip::ZipWriter::new(zip_file);
        let options: FileOptions<'_, ()> = FileOptions::default();
        zip.start_file("platinum_v2.json", options).unwrap();
        zip.write_all(
            br#"{
  "meta": { "version": "Platinum" },
  "commands": {}
}"#,
        )
        .unwrap();
        zip.finish().unwrap();

        let out = root.path().join("out");
        fs::create_dir_all(&out).unwrap();
        unpack_zip(fs::File::open(zip_path).unwrap(), &out).unwrap();

        assert!(out.join("platinum_v2.json").exists());
    }

    #[test]
    fn embedded_database_archive_contains_v2_files() {
        let out = tempdir().unwrap();
        unpack_zip(Cursor::new(EMBEDDED_COMMAND_DATABASE_ZIP), out.path()).unwrap();

        let mut files = Vec::new();
        collect_v2_files(out.path(), &mut files).unwrap();
        assert!(!files.is_empty());
    }
}
